version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - counter_data:/data
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped

volumes:
  counter_data: